### ISSUE TITLE
Loading a lot of rows containing merged cells slows down

### ISSUE THREAD

**Issue by fukasawah** [hishidama/embulk-parser-poi_excel#2]
I gave it 10,000 rows of data, it became very slow.

But, Setting `search_merged_cell: false` will work.
It looks like it slows down in proportion to the number of merged cells.

I think the following code is being processed on a per Cell basis and is slow.

https://github.com/hishidama/embulk-parser-poi_excel/blob/0db4cab1f9bff487e7e97adf8eae21a18ed19a9f/src/main/java/org/embulk/parser/poi_excel/visitor/PoiExcelCellValueVisitor.java#L86-L89

Test data and config.yml here. [reports.zip](https://github.com/hishidama/embulk-parser-poi_excel/files/4959935/reports.zip)

**Comment by hishidama** [comment]
In version 0.1.10, changed `search_merged_cell`  `false,true` to `none,linear_search,tree_search`. (default: `tree_search`)
tree_search is faster than linear_search, but uses a lot of memory.
